enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

#Morphe
[YouTube-Morphe]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
build-mode = "module"


#RVX
[YouTube-Extended]
enabled = true
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "module"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"

[IconPackStudio]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"
